//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alpha.DatabaseItems
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expence
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string NameAr { get; set; }
        public decimal Price { get; set; }
        public System.DateTime Date { get; set; }
    }
}
