//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alpha.DatabaseItems
{
    using System;
    using System.Collections.Generic;
    
    public partial class Installment
    {
        public int ID { get; set; }
        public int TransactionId { get; set; }
        public Nullable<int> NumberOfInstallments { get; set; }
        public Nullable<int> InstallmentEveryNumberOfMonths { get; set; }
        public Nullable<decimal> InstallmentCost { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<bool> IsDebt { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> SupplierId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Transaction Transaction { get; set; }
    }
}
